# ARQUIVO RESPONSÁVEL POR GUARDAR TODAS AS CONSTANTES - TODOS OS VALORES ESTÃO NO SI (SISTEMA INTERNACIONAL)

from math import pi
from numpy import sqrt
from scipy.constants import c

# CONSTANTES DO GUIA DE ONDA RETANGULAR WR-10

A_LARGURA = 2.54e-3
B_ALTURA = 1.27e-3

# CONSTANTES FÍSICAS

PERMESSIVIDADE_ELETRICA = 8.854e-12
PERMEABILIDADE_MAGNETICA = 4e-7 * pi
IMPEDANCIA_ESPACO_LIVRE = sqrt(PERMEABILIDADE_MAGNETICA / PERMESSIVIDADE_ELETRICA)
VELOCIDADE_LUZ_VACUO = c

# FAIXA DE OPERAÇÃO (FREQUÊNCIA)

FREQUENCIA_CORTE_TE_10 = 59.015e9

# PARÂMETROS DA GRADE FDTD

FATOR_ESTABILIDADE_COURANT = 0.99 / sqrt(2)

# RESOLUÇÃO ESPACIAL DO GRÁFICO

NUMERO_DIVISAO_GUIA = 40
DIMENSAO_X = A_LARGURA / NUMERO_DIVISAO_GUIA
DIMENSAO_Z = DIMENSAO_X

# RESOLUÇÃO TEMPORAL DO GRÁFICO

TEMPO = FATOR_ESTABILIDADE_COURANT * DIMENSAO_X / VELOCIDADE_LUZ_VACUO

# TAMANHO DO DOMÍNIO DA SIMULAÇÃO

COMPRIMENTO_Z = 15e-3
NUMERO_PONTOS_Z = int(COMPRIMENTO_Z / DIMENSAO_Z)
NUMERO_PONTOS_X = NUMERO_DIVISAO_GUIA

# PARÂMETROS DA FONTE

POSICAO_FONTE_EIXO_Z = 10

# VARIÁVEIS DE MENU (DEFINIDA DE ACORDO COM A OPÇÃO DE MENU SELECIONADA)

FREQUENCIA_OPERACAO = 0.0
NUMERO = 0 
LETRA = '*'
